version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: echo "🚀 Starting CircleCI Python Build"
      - run: python --version
      - run: pip install pytest
      - run: pytest test_hello.py
